version: "2"
linters:
  default: all
  disable:
    - depguard
    - exhaustruct
    - funcorder
    - gochecknoglobals
    - ireturn
    - mnd
    - nlreturn
    - noinlineerr
    - paralleltest
    - prealloc
    - revive
    - varnamelen
    - wrapcheck
    - wsl
    - wsl_v5
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
