linters:
  enable-all: true
  disable:
    - tagalign
    - gochecknoinits
    - bodyclose
    - depguard
    - exhaustruct
    - fatcontext
    - forcetypeassert
    - gochecknoglobals
    - ireturn
    - mnd
    - paralleltest
    - varnamelen
    - wrapcheck
    - tagliatelle
    - tenv
