version: 2.1

jobs:
  build:
    docker:
      - image: circleci/golang:1.15
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-health-mod-cache-{{ checksum "go.sum" }}
            - go-health-mod-cache-
      - run: make dep
      - save_cache:
          key: go-health-mod-cache-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run: make specs
      - run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.31.0
      - run: make lint

workflows:
  go-health:
    jobs:
      - build
