version: 2.1

jobs:
  build:
    docker:
      - image: alexfalkowski/go:1.15
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-health-mod-cache-{{ checksum "go.sum" }}
            - go-health-mod-cache-
      - run: make dep
      - save_cache:
          key: go-health-mod-cache-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run: make specs
      - run: make lint
  release:
    docker:
      - image: alexfalkowski/release:1.0
    steps:
      - checkout
      - run: release.sh

workflows:
  go-health:
    jobs:
      - build
      - release:
          requires:
            - build
          filters:
            branches:
              only: main
