version: 2.1

jobs:
  build:
    docker:
      - image: alexfalkowski/go:1.21-3.2
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: make dep
      - run: make lint
      - run: make sec
      - run: make specs
      - run: make goveralls
    resource_class: large
  release:
    docker:
      - image: alexfalkowski/release:3.1
    steps:
      - checkout
      - run: release
    resource_class: large

workflows:
  go-health:
    jobs:
      - build
      - release:
          context: gh
          requires:
            - build
          filters:
            branches:
              only: master
