version: 2.1

jobs:
  build:
    docker:
      - image: alexfalkowski/go:2.51
      - image: alexfalkowski/status:latest
        command: server -i env:CONFIG
        environment:
          CONFIG: yml:ZW52aXJvbm1lbnQ6IGRldmVsb3BtZW50CmhlYWx0aDoKICBkdXJhdGlvbjogMXMKICB0aW1lb3V0OiAxcwppZDoKICBraW5kOiB1dWlkCnRlbGVtZXRyeToKICBsb2dnZXI6CiAgICBraW5kOiB0ZXh0CiAgICBsZXZlbDogaW5mbwp0cmFuc3BvcnQ6CiAgaHR0cDoKICAgIGFkZHJlc3M6IHRjcDovLzo2MDAwCiAgICByZXRyeToKICAgICAgYmFja29mZjogMTAwbXMKICAgICAgdGltZW91dDogMXMKICAgICAgYXR0ZW1wdHM6IDMKICAgIHRpbWVvdXQ6IDEwcwogICAgdXNlcl9hZ2VudDogIlN0YXR1cy1zZXJ2ZXIvMS4wIGh0dHAvMS4wIgo=
    working_directory: ~/go-health
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: make source-key
      - restore_cache:
          name: restore go cache
          keys:
            - go-health-go-cache-{{ checksum "go.sum" }}-{{ checksum "~/.go-version" }}-{{ checksum ".source-key" }}
            - go-health-go-cache-
      - run: make clean
      - run: make dep
      - save_cache:
          name: save go cache
          key: go-health-go-cache-{{ checksum "go.sum" }}-{{ checksum "~/.go-version" }}-{{ checksum ".source-key" }}
          paths:
            - ~/go/pkg/mod
      - restore_cache:
          name: restore go build cache
          keys:
            - go-health-go-build-cache-{{ checksum "go.sum" }}-{{ checksum "~/.go-version" }}-{{ checksum ".source-key" }}
            - go-health-go-build-cache-
      - restore_cache:
          name: restore go lint cache
          keys:
            - go-health-go-lint-cache-{{ checksum "go.sum" }}-{{ checksum "~/.go-lint-version" }}-{{ checksum ".source-key" }}
            - go-health-go-lint-cache-
      - run: make clean
      - run: make lint
      - save_cache:
          name: save go lint cache
          key: go-health-go-lint-cache-{{ checksum "go.sum" }}-{{ checksum "~/.go-lint-version" }}-{{ checksum ".source-key" }}
          paths:
            - ~/.cache/golangci-lint
      - run: make sec
      - run: make specs
      - save_cache:
          name: save go build cache
          key: go-health-go-build-cache-{{ checksum "go.sum" }}-{{ checksum "~/.go-version" }}-{{ checksum ".source-key" }}
          paths:
            - ~/.cache/go-build
      - run: make coverage
      - store_test_results:
          path: test/reports
      - store_artifacts:
          path: test/reports
      - run: make codecov-upload
    resource_class: large
  version:
    docker:
      - image: alexfalkowski/release:5.7
    working_directory: ~/go-health
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: version
    resource_class: large

workflows:
  go-health:
    jobs:
      - build
      - version:
          context: gh
          requires:
            - build
          filters:
            branches:
              only: master
